buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.+'
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'idea'

version = mod_version
group = "git.str1llax.${mod_id}"
archivesBaseName = mod_id

sourceCompatibility = targetCompatibility = "1.8"
compileJava.options.encoding = "UTF-8"

minecraft {
    mappings channel: 'snapshot', version: '20171003-1.12'

    runs {
        client {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'

            jvmArg "${'minecraft.jvmargs'}"
        }

        server {
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'

            jvmArg "${'minecraft.jvmargs'}"
        }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
}

jar {
    archiveFileName = "${mod_id}-${minecraft_version}-${mod_version}.jar"

    destinationDirectory = file("${projectDir}/builds")

    manifest {
        attributes([
            "Specification-Title": mod_id,
            "Specification-Vendor": "Str1llax",
            "Specification-Version": "1",
            "Implementation-Title": project.name,
            "Implementation-Version": "${mod_version}",
            "Implementation-Vendor" :"Str1llax",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

idea {
    module {
        inheritOutputDirs = true
    }
}

jar.finalizedBy('reobfJar')

processResources {
    inputs.property "version", "${mod_version}"
    inputs.property "mcversion", "${minecraft_version}"

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'

        expand 'version': "${mod_version}", 'mcversion': "${minecraft_version}"
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}
